# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deployment pipeline

on:
  push:
  pull_request:
    branches: [main] # PRs que apuntan a main
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "16" # pon '20' si migraste a Node 20
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm test -- --ci
        env:
          CI: true

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Show event/ref (debug)
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && !contains((github.event.head_commit.message || ''), '#skip')
    steps:
      - name: Trigger deployment (Render Deploy Hook API)
        run: |
          set -e
          CODE=$(curl -sS -o /dev/null -w "%{http_code}" "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}")
          echo "Render API responded: $CODE"
          test "$CODE" = "200"
  tag_release:
    needs: [ci, deploy] # o solo [ci] si no quieres esperar al deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && !contains((github.event.head_commit.message || ''), '#skip')
    permissions:
      contents: write

    steps:
      - name: Checkout repo (with full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # importante para que existan los tags y el historial

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch # por defecto sube el PATCH
          WITH_V: true # tags tipo v1.2.3 (opcional)
          # DRY_RUN: "true"     # activa si quieres probar sin crear tag real
